### ISSUE TITLE
Tip Suggestion: "Players can press C to open their character sheet. GMs can open the character sheet of the token they control by pressing C also."

### ISSUE THREAD

**Issue by Norc** [vttred/tips#38]
Pretty sure this is system agnostic, not documented anywhere, and super handy.

**Comment by anthonyronda** [comment]
Hey we don't have this one! Thx

**Comment by Norc** [comment]
I know! I _checked_ this time. Look at me go.

**Comment by anthonyronda** [comment]
This is accepted for use as a core tip. Closing this before implementing it because I'd like any new tippers to use the brand new issue template, and I don't want them to see yours and get jealous that you didn't have to
