### ISSUE TITLE
Tip Suggestion: Initial View Position

### ISSUE THREAD

**Issue by Norc** [vttred/tips#39]
"You can configure a scene to have an Initial View Position that players see when they load in. However, if a player owns a token on that scene, their view will always be centered on their token instead."

I was today years old when Iearned this one myself (the second part).

**Comment by anthonyronda** [comment]
This is accepted for use as a core tip.

Closing this before implementing it because I'd like any new tippers to use the brand new issue template, and I don't want them to see yours and get jealous that you didn't have to
